### ISSUE TITLE
The compiled file fails to execute filestream operations

### ISSUE THREAD

**Issue by adiultra** [kriscross07/atom-gpp-compiler#17]
I am using atom v1.7.3, g++ v5.2.1.

My Problem is that when I compile and run the program given below, It does not work:

```c++
#include <iostream>
#include <fstream>

using namespace std;

int main() {
    ofstream file("myFile.txt"); // I do already have tried with and without this file in the folder

    file << "Amazing";

    file.close();

    return 0;
}

```

Where as when I use
```bash
$ g++ file-handling.cpp
$ ./a.out
```

It works perfectly.

I run Ubuntu mate 15.10.

**Comment by kriscross07** [comment]
Are you having issues compiling the program, running it, or just not getting the expected results?

If you are using GNOME Terminal, there is no option to hold the terminal open after the command completes, so if the program completes nearly instantly, you may not see the terminal appear.
Try setting XTerm as your default terminal inside the package settings or add a `while (true);` directly before your `return 0;` to keep the program running until you close it.

The file may be created, but just not in the right spot since your program creates the file in the working directory it was started from. Look in your home directory or run `find ~ -name myFile.txt` in your shell, which will search for every file name in your home directory recursively and print it to stdout if it finds a file called `myFile.txt`.

**Comment by adiultra** [comment]
Well I use x-term and the file is not made. The changes in the file do not happen.
The programs comiles and when run only shows black terminal (which is fine since I have used no cout) but it does not do waht it is programmed to do.

Also Note : _The file is present in a subfolder of the current project folder_

**Comment by kriscross07** [comment]
From the terminal, enter `g++ src/subdirectory/source.cpp && ./a.out` in your home directory (replacing `src/subdirectory/source.cpp` with your C++ file) and tell me if it works or not.

**Comment by adiultra** [comment]
I already told you it does, g++ compiles fine and the program works as expected when compiled through terminal

**Comment by kriscross07** [comment]
Does v2.2.2 fix the issue?

**Comment by adiultra** [comment]
Yes it Does, Many many thanks for it.
