### ISSUE TITLE
Can't see compiled C files

### ISSUE THREAD

**Issue by aotsishd** [kriscross07/atom-gpp-compiler#34]
This is probably a really dumb issue so please bare with me.
I compiled a file named testx.c and ran it through the F5 command. However, I can't see the compiled .exe file on the directory.
<img width="501" alt="screenshot_14" src="https://cloud.githubusercontent.com/assets/21256241/17996262/4417a844-6b2d-11e6-87cf-23e02ebe25ac.png">

I tried disabling the "Run After Compile" option and all i got was a "Compilation succesful" notification, yet I couldn't find the compiled .exe file. Is this behavior normal or am I missing something?

**Comment by kriscross07** [comment]
In v3.0.0, it changed from where it would compile to the source directory, to where it would compile to a temporary directory to avoid overwriting files. I agree that it makes no sense to compile to a temporary directory when the `Run After Compile` option is disabled. I will add an option to compile to the source directory in v3.0.1.

Unrelated, but it seems like you're using a non-[monospaced font](https://en.wikipedia.org/wiki/Monospaced_font). Is that intentional?
